### ISSUE TITLE
How to use the code?

### ISSUE THREAD

**Issue by rahulk31** [Code-Bullet/Google-Chrome-Dino-Game-AI#3]
How to use the provided code? please guide me hoe can I use the code and play the AI game? on which IDE to paste the code? I'm a beginner in this field please guide me.
Thank you!

**Comment by aatesh99** [comment]
1) download processing software 
2) download this code 
3)open the code using processing software 
4)you need to open all the text files or classes and u need to run the dino game class for it to run

**Comment by rahulk31** [comment]
Which one is the processing software for this that I need to download?

**Comment by aatesh99** [comment]
You can download the latest update to the software just check whether your pc is 32 bit or 64 bit and make sure it is compatible with your os as well

**Comment by rahulk31** [comment]
I have downloaded the python 3.6.5 version and installed now I want to know how to use these files in my IDE. The IDE which I'm using is VScode

**Comment by skyfeature** [comment]
@settingsingh You need [this one](https://processing.org/). Follow the steps:  
1. If you are on windows and if your computer is less than 6 years old, [click here](http://download.processing.org/processing-3.4-windows64.zip) to download 64bit it otherwise [click here](http://download.processing.org/processing-3.4-windows32.zip) to download 32 bit version.   

2. Unzip the file. You will get a folder whose name contains 'processing'  
3. Go into that folder.  
4. Into that folder, you will find a file named 'processing'.  
5. Double click on 'processing' file to run it.  
6. Follow step 3 and step 4 from [aatesh99's comment](https://github.com/Code-Bullet/Google-Chrome-Dino-Game-AI/issues/3#issuecomment-414324342)  

P.S: learn from [official website](https://processing.org/tutorials/gettingstarted/). It's an awesome software.

**Comment by rahulk31** [comment]
thank you guys @aatesh99 @skyfeature
